### PR TITLE
fix: Update Watopia map

### PR DESCRIPTION
**Pull request by Strajk**
Heya 👋

I've noticed you [reported](https://forums.zwift.com/t/outdated-watopia-map-image/585073) an outdated watopia map a long time ago.
Web uses outdated [CDN](https://cdn.zwift.com/static/images/maps/MiniMap_Watopia.png) (found in zwift-data repo, thx!), but new maps are bundled in mobile companion apps so I took them from there ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by andipaetzold** [comment]
Awesome! Thanks a lot. <3 

I checked the Android companion app before and only found the map as individual tiles. Merging those created a very big image because of color pallets and bad compression. 

Could you extract the map of Makuri Islands as well? It's quality on the web is very bad they also don't update it there :(

**Comment by Strajk** [comment]
Yep yep, same approach. Will do Maruki, np.

I've merged the tiles using ChatGPT 😆, checked what compression is used on PNGs hosted on CDN, and then used [Image Optim](https://imageoptim.com/mac) to compress the merged result with similar options.
Luckily there were no problems with compression as I would probably not know how to handle these. 

Fo7aUp8WYAEg6dY

**Comment by andipaetzold** [comment]
Okay, I assumed the companion app already had the full image. I attempted the merge with imagemagick, but the final images were quite big.

When zooming in, you can see these a few dots with the wrong colors. I am not an image expert, but they somehow always show up when compressing Zwift's maps. The current CDN-version of Makuri Islands has the same dots...

image

Still, the image is probably better than having an outdated version of the map.

**Comment by Strajk** [comment]
good catch – will check!

**Comment by Strajk** [comment]
No solution yet, just debugging:

* Android app contains tiles in jpg, not png :/
image

* even these already contain slight compression artifacts 
Screen 2023-02-14 at 19 31 22

* same artifacts after merging tiles
Screen 2023-02-14 at 19 32 38

* final harsh artifacts after aggressive compression (to match filesize from cdn)
Screen 2023-02-14 at 19 33 35

**Comment by andipaetzold** [comment]
I ran `magick identify -verbose watopia.png` against both files

As you can see in the diff, the original image uses a Colormap with exactly 22 colors. That's how the small size is achieved without loosing quality. Every used color is exactly defined in that colormap. The new image uses way more colors and therefore has to compress quite a lot and looses quality.

I did my tests a while ago and I don't remember exactly how my images looked, but I feel like this is somewhat the same result.

```patch
diff --git a/watopia-old.txt b/watopia-new.txt
index 8b33719b..23402658 100644
--- a/watopia-old.txt
+++ b/watopia-new.txt
@@ -17,164 +17,90 @@ Image:
   Channel statistics:
     Pixels: 33554432
     Red:
-      min: 8  (0.0313725)
-      max: 252 (0.988235)
-      mean: 100.406 (0.393747)
+      min: 9  (0.0352941)
+      max: 241 (0.945098)
+      mean: 100.227 (0.393048)
       median: 87 (0.341176)
-      standard deviation: 74.9816 (0.294045)
-      kurtosis: -0.9041
-      skewness: 0.545219
-      entropy: 0.608456
+      standard deviation: 75.1365 (0.294653)
+      kurtosis: -0.920985
+      skewness: 0.5559
+      entropy: 0.756465
     Green:
-      min: 51  (0.2)
-      max: 242 (0.94902)
-      mean: 160.416 (0.629083)
+      min: 65  (0.254902)
+      max: 216 (0.847059)
+      mean: 160.465 (0.629273)
       median: 156 (0.611765)
-      standard deviation: 26.8373 (0.105244)
-      kurtosis: 0.533912
-      skewness: -0.407873
-      entropy: 0.62577
+      standard deviation: 27.0335 (0.106014)
+      kurtosis: 0.504999
+      skewness: -0.401318
+      entropy: 0.767242
     Blue:
-      min: 24  (0.0941176)
-      max: 228 (0.894118)
-      mean: 161.728 (0.634226)
-      median: 196 (0.768627)
-      standard deviation: 63.0955 (0.247433)
-      kurtosis: -1.30205
-      skewness: -0.556037
-      entropy: 0.611489
+      min: 57  (0.223529)
+      max: 227 (0.890196)
+      mean: 161.968 (0.63517)
+      median: 195 (0.764706)
+      standard deviation: 62.1595 (0.243763)
+      kurtosis: -1.30106
+      skewness: -0.559292
+      entropy: 0.76248
   Image statistics:
     Overall:
-      min: 8  (0.0313725)
-      max: 252 (0.988235)
-      mean: 140.85 (0.552352)
-      median: 146.333 (0.573856)
-      standard deviation: 54.9714 (0.215574)
-      kurtosis: -0.872571
-      skewness: -0.429061
-      entropy: 0.615238
-  Colors: 59
+      min: 9  (0.0352941)
+      max: 241 (0.945098)
+      mean: 140.887 (0.552497)
+      median: 146 (0.572549)
+      standard deviation: 54.7765 (0.21481)
+      kurtosis: -0.881811
+      skewness: -0.432341
+      entropy: 0.762063
+  Colors: 22
   Histogram:
-       5445740: (8,134,228) #0886E4 srgb(8,134,228)
-       3354927: (43,163,221) #2BA3DD srgb(43,163,221)
-          1129: (43,196,133) #2BC485 srgb(43,196,133)
-       6670703: (49,191,196) #31BFC4 srgb(49,191,196)
-           282: (50,193,76) #32C14C srgb(50,193,76)
-           153: (51,51,51) #333333 grey20
-          7615: (56,99,109) #38636D srgb(56,99,109)
-         15258: (57,156,173) #399CAD srgb(57,156,173)
-          1441: (57,161,200) #39A1C8 srgb(57,161,200)
-        280693: (66,66,66) #424242 grey26
-          4887: (73,74,74) #494A4A srgb(73,74,74)
-          6887: (74,82,82) #4A5252 srgb(74,82,82)
-         34992: (82,74,73) #524A49 srgb(82,74,73)
-         52561: (83,82,81) #535251 srgb(83,82,81)
-          9267: (83,172,199) #53ACC7 srgb(83,172,199)
-          1050: (83,174,122) #53AE7A srgb(83,174,122)
-          2787: (84,126,157) #547E9D srgb(84,126,157)
-       2579975: (87,140,96) #578C60 srgb(87,140,96)
-         25621: (90,99,101) #5A6365 srgb(90,99,101)
-         73671: (91,89,74) #5B594A srgb(91,89,74)
-           703: (96,107,115) #606B73 srgb(96,107,115)
-         47417: (99,115,123) #63737B srgb(99,115,123)
-         30033: (102,104,104) #666868 srgb(102,104,104)
-         28676: (105,143,105) #698F69 srgb(105,143,105)
-         10213: (108,157,128) #6C9D80 srgb(108,157,128)
-         94523: (114,82,73) #725249 srgb(114,82,73)
-        180277: (115,115,115) #737373 grey45
-         57570: (115,148,57) #739439 srgb(115,148,57)
-          3721: (120,107,101) #786B65 srgb(120,107,101)
-         37761: (122,99,76) #7A634C srgb(122,99,76)
-       4456646: (124,153,56) #7C9938 srgb(124,153,56)
-          2275: (125,81,49) #7D5131 srgb(125,81,49)
-          5179: (131,150,131) #839683 srgb(131,150,131)
-          9470: (135,123,115) #877B73 srgb(135,123,115)
-         21945: (144,108,80) #906C50 srgb(144,108,80)
-       2358806: (145,177,200) #91B1C8 srgb(145,177,200)
-        226254: (148,115,107) #94736B srgb(148,115,107)
-          7627: (148,140,104) #948C68 srgb(148,140,104)
-         12456: (148,149,144) #949590 srgb(148,149,144)
-          9441: (155,135,125) #9B877D srgb(155,135,125)
-        120173: (156,156,156) #9C9C9C grey61
-        185167: (165,126,101) #A57E65 srgb(165,126,101)
-        443498: (173,99,57) #AD6339 srgb(173,99,57)
-        262478: (173,222,222) #ADDEDE srgb(173,222,222)
-         21514: (174,146,134) #AE9286 srgb(174,146,134)
-         36566: (174,156,86) #AE9C56 srgb(174,156,86)
-         18769: (179,176,149) #B3B095 srgb(179,176,149)
-         23619: (181,183,177) #B5B7B1 srgb(181,183,177)
-         11055: (182,170,126) #B6AA7E srgb(182,170,126)
-          3830: (189,66,24) #BD4218 srgb(189,66,24)
-         45814: (190,194,182) #BEC2B6 srgb(190,194,182)
-       2110598: (201,201,201) #C9C9C9 grey79
-         47553: (208,152,111) #D0986F srgb(208,152,111)
-         20268: (208,174,145) #D0AE91 srgb(208,174,145)
-        448553: (214,165,115) #D6A573 srgb(214,165,115)
-           672: (224,214,205) #E0D6CD srgb(224,214,205)
-         15837: (232,150,112) #E89670 srgb(232,150,112)
-       3566211: (241,156,117) #F19C75 srgb(241,156,117)
-          1625: (252,242,217) #FCF2D9 srgb(252,242,217)
-  Colormap entries: 59
+       5447947: (9,134,227) #0986E3 srgb(9,134,227)
+       3356205: (44,163,221) #2CA3DD srgb(44,163,221)
+       6740088: (47,192,195) #2FC0C3 srgb(47,192,195)
+         27942: (64,159,169) #409FA9 srgb(64,159,169)
+        393329: (66,65,65) #424141 srgb(66,65,65)
+       2565370: (87,140,96) #578C60 srgb(87,140,96)
+        210988: (103,91,80) #675B50 srgb(103,91,80)
+        106042: (110,145,78) #6E914E srgb(110,145,78)
+         22383: (112,204,207) #70CCCF srgb(112,204,207)
+        340550: (113,115,116) #717374 srgb(113,115,116)
+         30389: (117,154,145) #759A91 srgb(117,154,145)
+       4293559: (125,152,57) #7D9839 srgb(125,152,57)
+       2359553: (145,177,200) #91B1C8 srgb(145,177,200)
+        272217: (147,119,108) #93776C srgb(147,119,108)
+        139801: (152,154,152) #989A98 srgb(152,154,152)
+        265091: (174,216,217) #AED8D9 srgb(174,216,217)
+        606222: (175,108,66) #AF6C42 srgb(175,108,66)
+         97081: (177,151,107) #B1976B srgb(177,151,107)
+         64077: (190,181,161) #BEB5A1 srgb(190,181,161)
+       2137142: (201,201,201) #C9C9C9 grey79
+        497845: (214,160,116) #D6A074 srgb(214,160,116)
+       3580611: (241,156,117) #F19C75 srgb(241,156,117)
+  Colormap entries: 22
   Colormap:
-    0: (49,191,196,1) #31BFC4FF srgba(49,191,196,1)
-    1: (8,134,228,1) #0886E4FF srgba(8,134,228,1)
-    2: (124,153,56,1) #7C9938FF srgba(124,153,56,1)
-    3: (241,156,117,1) #F19C75FF srgba(241,156,117,1)
-    4: (43,163,221,1) #2BA3DDFF srgba(43,163,221,1)
-    5: (87,140,96,1) #578C60FF srgba(87,140,96,1)
-    6: (145,177,200,1) #91B1C8FF srgba(145,177,200,1)
-    7: (201,201,201,1) #C9C9C9FF grey79
-    8: (214,165,115,1) #D6A573FF srgba(214,165,115,1)
-    9: (173,99,57,1) #AD6339FF srgba(173,99,57,1)
-    10: (66,66,66,1) #424242FF grey26
-    11: (173,222,222,1) #ADDEDEFF srgba(173,222,222,1)
-    12: (148,115,107,1) #94736BFF srgba(148,115,107,1)
-    13: (165,126,101,1) #A57E65FF srgba(165,126,101,1)
-    14: (115,115,115,1) #737373FF grey45
-    15: (156,156,156,1) #9C9C9CFF grey61
-    16: (114,82,73,1) #725249FF srgba(114,82,73,1)
-    17: (91,89,74,1) #5B594AFF srgba(91,89,74,1)
-    18: (115,148,57,1) #739439FF srgba(115,148,57,1)
-    19: (83,82,81,1) #535251FF srgba(83,82,81,1)
-    20: (208,152,111,1) #D0986FFF srgba(208,152,111,1)
-    21: (99,115,123,1) #63737BFF srgba(99,115,123,1)
-    22: (190,194,182,1) #BEC2B6FF srgba(190,194,182,1)
-    23: (122,99,76,1) #7A634CFF srgba(122,99,76,1)
-    24: (174,156,86,1) #AE9C56FF srgba(174,156,86,1)
-    25: (82,74,73,1) #524A49FF srgba(82,74,73,1)
-    26: (102,104,104,1) #666868FF srgba(102,104,104,1)
-    27: (105,143,105,1) #698F69FF srgba(105,143,105,1)
-    28: (90,99,101,1) #5A6365FF srgba(90,99,101,1)
-    29: (181,183,177,1) #B5B7B1FF srgba(181,183,177,1)
-    30: (144,108,80,1) #906C50FF srgba(144,108,80,1)
-    31: (174,146,134,1) #AE9286FF srgba(174,146,134,1)
-    32: (208,174,145,1) #D0AE91FF srgba(208,174,145,1)
-    33: (179,176,149,1) #B3B095FF srgba(179,176,149,1)
-    34: (232,150,112,1) #E89670FF srgba(232,150,112,1)
-    35: (57,156,173,1) #399CADFF srgba(57,156,173,1)
-    36: (148,149,144,1) #949590FF srgba(148,149,144,1)
-    37: (182,170,126,1) #B6AA7EFF srgba(182,170,126,1)
-    38: (108,157,128,1) #6C9D80FF srgba(108,157,128,1)
-    39: (135,123,115,1) #877B73FF srgba(135,123,115,1)
-    40: (155,135,125,1) #9B877DFF srgba(155,135,125,1)
-    41: (83,172,199,1) #53ACC7FF srgba(83,172,199,1)
-    42: (148,140,104,1) #948C68FF srgba(148,140,104,1)
-    43: (56,99,109,1) #38636DFF srgba(56,99,109,1)
-    44: (74,82,82,1) #4A5252FF srgba(74,82,82,1)
-    45: (131,150,131,1) #839683FF srgba(131,150,131,1)
-    46: (73,74,74,1) #494A4AFF srgba(73,74,74,1)
-    47: (189,66,24,1) #BD4218FF srgba(189,66,24,1)
-    48: (120,107,101,1) #786B65FF srgba(120,107,101,1)
-    49: (84,126,157,1) #547E9DFF srgba(84,126,157,1)
-    50: (125,81,49,1) #7D5131FF srgba(125,81,49,1)
-    51: (252,242,217,1) #FCF2D9FF srgba(252,242,217,1)
-    52: (57,161,200,1) #39A1C8FF srgba(57,161,200,1)
-    53: (43,196,133,1) #2BC485FF srgba(43,196,133,1)
-    54: (83,174,122,1) #53AE7AFF srgba(83,174,122,1)
-    55: (96,107,115,1) #606B73FF srgba(96,107,115,1)
-    56: (224,214,205,1) #E0D6CDFF srgba(224,214,205,1)
-    57: (50,193,76,1) #32C14CFF srgba(50,193,76,1)
-    58: (51,51,51,1) #333333FF grey20
+    0: (9,134,227,1) #0986E3FF srgba(9,134,227,1)
+    1: (44,163,221,1) #2CA3DDFF srgba(44,163,221,1)
+    2: (47,192,195,1) #2FC0C3FF srgba(47,192,195,1)
+    3: (117,154,145,1) #759A91FF srgba(117,154,145,1)
+    4: (241,156,117,1) #F19C75FF srgba(241,156,117,1)
+    5: (64,159,169,1) #409FA9FF srgba(64,159,169,1)
+    6: (190,181,161,1) #BEB5A1FF srgba(190,181,161,1)
+    7: (152,154,152,1) #989A98FF srgba(152,154,152,1)
+    8: (112,204,207,1) #70CCCFFF srgba(112,204,207,1)
+    9: (214,160,116,1) #D6A074FF srgba(214,160,116,1)
+    10: (145,177,200,1) #91B1C8FF srgba(145,177,200,1)
+    11: (174,216,217,1) #AED8D9FF srgba(174,216,217,1)
+    12: (201,201,201,1) #C9C9C9FF grey79
+    13: (177,151,107,1) #B1976BFF srgba(177,151,107,1)
+    14: (87,140,96,1) #578C60FF srgba(87,140,96,1)
+    15: (113,115,116,1) #717374FF srgba(113,115,116,1)
+    16: (147,119,108,1) #93776CFF srgba(147,119,108,1)
+    17: (110,145,78,1) #6E914EFF srgba(110,145,78,1)
+    18: (175,108,66,1) #AF6C42FF srgba(175,108,66,1)
+    19: (103,91,80,1) #675B50FF srgba(103,91,80,1)
+    20: (125,152,57,1) #7D9839FF srgba(125,152,57,1)
+    21: (66,65,65,1) #424141FF srgba(66,65,65,1)
   Rendering intent: Perceptual
   Gamma: 0.454545
   Chromaticity:
@@ -195,24 +121,24 @@ Image:
   Compression: Zip
   Orientation: Undefined
   Properties:
-    date:create: 2023-02-14T18:41:23+00:00
-    date:modify: 2023-02-14T18:41:23+00:00
-    date:timestamp: 2023-02-14T18:41:27+00:00
+    date:create: 2023-02-14T18:40:21+00:00
+    date:modify: 2023-02-14T18:40:21+00:00
+    date:timestamp: 2023-02-14T18:40:49+00:00
     png:IHDR.bit-depth-orig: 8
     png:IHDR.bit_depth: 8
     png:IHDR.color-type-orig: 3
     png:IHDR.color_type: 3 (Indexed)
     png:IHDR.interlace_method: 0 (Not interlaced)
     png:IHDR.width,height: 8192, 4096
-    png:PLTE.number_colors: 59
-    signature: 4e5b41feae52fb92eca343ef6c6d3af10df99dee61f96e75f243d340f261d8dd
+    png:PLTE.number_colors: 22
+    signature: df637af1bdfd5a637fcd62a453ab334bff2152650bf21846f4f075f20b0799e4
   Artifacts:
     verbose: true
   Tainted: False
-  Filesize: 884505B
+  Filesize: 963623B
   Number pixels: 33.5544M
   Pixel cache type: Memory
-  Pixels per second: 143.212MP
-  User time: 0.230u
-  Elapsed time: 0:01.234
+  Pixels per second: 137.657MP
+  User time: 0.240u
+  Elapsed time: 0:01.243
   Version: ImageMagick 7.1.0-61 Q16-HDRI aarch64 20866 https://imagemagick.org
```

**Comment by Strajk** [comment]
iOS app contains all maps in png, already merged, up to date, and with perfect details ⭐️

image

Screen 2023-02-14 at 20 04 03

Now let's just compress these :) Custom color maps sound like something Photoshop should have, I'll start the beast and explore :)

**Comment by Strajk** [comment]
> magick identify ...

cool trick, thx!
To clarify: the CDN version has 59 colors, my initial compressed version has 22 (max settings with ImageOptim)

I've tried different approaches of compressing the iOS originals – the result is not perfect and slightly bigger than the original – but my image processing skills are depleted :) 

* Photoshop – was unable to find a way how to limit number of colors in palette without picking them manually
* ImageOptim UI – weird "sharp" artifacts with various settings
* pngquant – also "sharp" artifacts, cmd `pngquant --quality=50-60 ios.png`
* https://kraken.io/ – also artifacts
* ⭐️ https://www.photopea.com – most basic UI, but the best results (recommended on HackerNews)

image

example of "sharp" artifacts 

image

---

Attaching both compressed result and original iOS assets, if u wanna give it a shot.

[photopea-7.png.zip](https://github.com/andipaetzold/zwiftmap/files/10740921/photopea-7.png.zip)

[watopia ios orig.png.zip](https://github.com/andipaetzold/zwiftmap/files/10740950/watopia.ios.orig.png.zip)

---

Whatcha think? I would go with the Photopea version until Zwift releases the official version on CDN.

**Comment by andipaetzold** [comment]
> > magick identify ...
> 
> cool trick, thx! To clarify: the CDN version has 59 colors, my initial compressed version has 22 (max settings with ImageOptim)

You are right... somehow failed to read my own diff 😆 

> Whatcha think? I would go with the Photopea version until Zwift releases the official version on CDN.

This situation is quite unsatisfying, but having the roads on the map is probably more important than having the best quality. I'll play around a bit with the iOS files and see whether I manage to achieve something. If not, I'd also go for photopea.

**Comment by Strajk** [comment]
> I'll play around a bit 

Great! If you wouldn't mind sharing some notes afterward, I would definitely be interested!

Here are all on the ios pngs in original resolution – I only ride Watopia so don't know what's wrong with Makuri.

[Archive.zip](https://github.com/andipaetzold/zwiftmap/files/10765397/Archive.zip)
[Archive 2.zip](https://github.com/andipaetzold/zwiftmap/files/10765398/Archive.2.zip)

**Pull request closed without merging**
